name:                erc20
version:             0.1.0.0
github:              "githubuser/erc20"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/erc20#readme>

dependencies:
  - base >= 4.7 && < 5
  - basement >0.0  && <0.1
  - cereal >0.5  && <0.6
  - text >1.2  && <1.3
  - memory >0.14 && <0.16
  - hashtables >1.0 && < 1.4
  - vector >0.12 && <0.13
  - bytestring >=0.10.12.0 && < 0.11.0.0

extra-deps:
  - container >=0.6.0 && < 0.7.0

library:
  source-dirs: src

executables:
  erc20-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - erc20

tests:
  erc20-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - erc20
